version: '3.8'

services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./.bin/main
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_POSTGRES_PASSWORD}
      - GIN_MODE=release

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - TZ=Europe/Moscow
    ports:
      - 5432:5432
